stages:
  - stage: build
    displayName: Build VSIX
    jobs:
      - job: Build
        pool:
          vmimage: ubuntu-latest
        steps: 
        - task: GitVersion@5
          inputs:
            runtime: 'core'

        - task: NodeTool@0
          inputs:
            versionSpec: '10.x'
          displayName: 'Install Node.js'

        - script: |
            npm install
            npm run build
          displayName: 'npm install and build'
          workingDirectory: ./Extension

        - script: |
            npm run package
          workingDirectory: ./Extension

        - task: TfxInstaller@2
          inputs:
            version: 'v0.6.x'

        - task: PackageAzureDevOpsExtension@2
          inputs:
            rootFolder: './Extension'
            outputPath: '$(Build.ArtifactStagingDirectory)/Pester.vsix'
            updateTasksVersion: true
            extensionVersion: $(GitVersion.MajorMinorPatch)

        - task: PublishBuildArtifacts@1
          displayName: 'Publish Artifact: vsix'
          inputs:
            PathtoPublish: '$(Build.ArtifactStagingDirectory)'
            ArtifactName: vsix
